/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Location { 'city' : string, 'address' : string }
export interface Message {
  'id' : bigint,
  'requestId' : bigint,
  'content' : string,
  'isRead' : boolean,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface Rating {
  'requestId' : bigint,
  'studentUserId' : Principal,
  'createdAt' : Time,
  'score' : bigint,
  'comment' : string,
  'helperUserId' : Principal,
}
export type RequestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface RequestWithTextTasks {
  'id' : bigint,
  'status' : RequestStatus,
  'tasks' : Array<string>,
  'title' : string,
  'submissionLocation' : [] | [string],
  'owner' : Principal,
  'createdAt' : Time,
  'description' : string,
  'assignedHelper' : [] | [Principal],
  'submissionMode' : SubmissionMode,
  'locationInfo' : [] | [Location],
}
export type SubmissionMode = { 'offline' : null } |
  { 'online' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'biography' : [] | [string],
  'organization' : [] | [string],
  'skills' : [] | [string],
}
export type UserRole = { 'helper' : null } |
  { 'client' : null } |
  { 'admin' : null } |
  { 'business' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRating' : ActorMethod<[bigint, Principal, bigint, string], undefined>,
  'addTask' : ActorMethod<[bigint, string], undefined>,
  'approveRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'completeInitialization' : ActorMethod<[], undefined>,
  'createWorkRequest' : ActorMethod<
    [string, string, [] | [Location], SubmissionMode],
    bigint
  >,
  'deleteRequest' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'filterRequestsByCity' : ActorMethod<[string], Array<RequestWithTextTasks>>,
  'getAllRatings' : ActorMethod<[], Array<Rating>>,
  'getAllRequests' : ActorMethod<[], Array<RequestWithTextTasks>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'totalRatings' : bigint,
      'completedRequests' : bigint,
      'averageRating' : number,
      'pendingRequests' : bigint,
      'totalUsers' : bigint,
      'acceptedRequests' : bigint,
      'totalRequests' : bigint,
    }
  >,
  'getAvailableRequests' : ActorMethod<[], Array<RequestWithTextTasks>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  'getMyAssignedRequests' : ActorMethod<[], Array<RequestWithTextTasks>>,
  'getMyRatingsAsHelper' : ActorMethod<[], Array<Rating>>,
  'getMyRequests' : ActorMethod<[], Array<RequestWithTextTasks>>,
  'getPendingRequestsForUser' : ActorMethod<
    [Principal],
    Array<RequestWithTextTasks>
  >,
  'getRatingsByUser' : ActorMethod<[Principal], Array<Rating>>,
  'getRequestsByStatus' : ActorMethod<
    [RequestStatus],
    Array<RequestWithTextTasks>
  >,
  'getTelegramConfigStatus' : ActorMethod<
    [],
    { 'isConfigured' : boolean, 'chatId' : [] | [string] }
  >,
  'getUnreadMessageCount' : ActorMethod<[bigint], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[bigint], undefined>,
  'rejectRequest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], string>,
  'sendMessage' : ActorMethod<[bigint, string], bigint>,
  'setTelegramConfig' : ActorMethod<[string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];