/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Record({ 'city' : IDL.Text, 'address' : IDL.Text });
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const RequestWithTextTasks = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'tasks' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'assignedHelper' : IDL.Opt(IDL.Principal),
  'locationInfo' : IDL.Opt(Location),
});
export const Rating = IDL.Record({
  'requestId' : IDL.Nat,
  'studentUserId' : IDL.Principal,
  'createdAt' : Time,
  'score' : IDL.Nat,
  'comment' : IDL.Text,
  'helperUserId' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'helper' : IDL.Null,
  'admin' : IDL.Null,
  'business' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'biography' : IDL.Opt(IDL.Text),
  'organization' : IDL.Opt(IDL.Text),
  'skills' : IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'requestId' : IDL.Nat,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRequest' : IDL.Func([IDL.Nat], [], []),
  'addRating' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'addTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'completeRequest' : IDL.Func([IDL.Nat], [], []),
  'createRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(Location)],
      [IDL.Nat],
      [],
    ),
  'deleteRequest' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'filterRequestsByCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RequestWithTextTasks)],
      ['query'],
    ),
  'getAllRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(RequestWithTextTasks)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalRatings' : IDL.Nat,
          'completedRequests' : IDL.Nat,
          'averageRating' : IDL.Float64,
          'pendingRequests' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'acceptedRequests' : IDL.Nat,
          'totalRequests' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAvailableRequests' : IDL.Func(
      [],
      [IDL.Vec(RequestWithTextTasks)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMyAssignedRequests' : IDL.Func(
      [],
      [IDL.Vec(RequestWithTextTasks)],
      ['query'],
    ),
  'getMyRatingsAsHelper' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
  'getMyRequests' : IDL.Func([], [IDL.Vec(RequestWithTextTasks)], ['query']),
  'getPendingRequestsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(RequestWithTextTasks)],
      ['query'],
    ),
  'getRatingsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
  'getRequestsByStatus' : IDL.Func(
      [RequestStatus],
      [IDL.Vec(RequestWithTextTasks)],
      ['query'],
    ),
  'getUnreadMessageCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Record({ 'city' : IDL.Text, 'address' : IDL.Text });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const RequestWithTextTasks = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'tasks' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'assignedHelper' : IDL.Opt(IDL.Principal),
    'locationInfo' : IDL.Opt(Location),
  });
  const Rating = IDL.Record({
    'requestId' : IDL.Nat,
    'studentUserId' : IDL.Principal,
    'createdAt' : Time,
    'score' : IDL.Nat,
    'comment' : IDL.Text,
    'helperUserId' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'helper' : IDL.Null,
    'admin' : IDL.Null,
    'business' : IDL.Null,
    'student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'biography' : IDL.Opt(IDL.Text),
    'organization' : IDL.Opt(IDL.Text),
    'skills' : IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'requestId' : IDL.Nat,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRequest' : IDL.Func([IDL.Nat], [], []),
    'addRating' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'addTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'completeRequest' : IDL.Func([IDL.Nat], [], []),
    'createRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(Location)],
        [IDL.Nat],
        [],
      ),
    'deleteRequest' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'filterRequestsByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RequestWithTextTasks)],
        ['query'],
      ),
    'getAllRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(RequestWithTextTasks)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalRatings' : IDL.Nat,
            'completedRequests' : IDL.Nat,
            'averageRating' : IDL.Float64,
            'pendingRequests' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'acceptedRequests' : IDL.Nat,
            'totalRequests' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAvailableRequests' : IDL.Func(
        [],
        [IDL.Vec(RequestWithTextTasks)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getMyAssignedRequests' : IDL.Func(
        [],
        [IDL.Vec(RequestWithTextTasks)],
        ['query'],
      ),
    'getMyRatingsAsHelper' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
    'getMyRequests' : IDL.Func([], [IDL.Vec(RequestWithTextTasks)], ['query']),
    'getPendingRequestsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(RequestWithTextTasks)],
        ['query'],
      ),
    'getRatingsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Rating)],
        ['query'],
      ),
    'getRequestsByStatus' : IDL.Func(
        [RequestStatus],
        [IDL.Vec(RequestWithTextTasks)],
        ['query'],
      ),
    'getUnreadMessageCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };